Sort string
js-tasks-ru/js-20230117_udjin pull request #2
Opened 2023-01-21 10:45 UTC by udjin89

2023-01-21 10:46 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-01-23 08:55 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.html
> +<!DOCTYPE html>
Этого файла не должно быть в PR

2023-01-23 08:56 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  let nArr = arr.slice(0, arr.length);
копирование массива следует осуществить вот так:
```
const copy = [...arr]
```

2023-01-23 08:56 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  return nArr.sort(comparator).reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2023-01-23 08:56 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2023-01-26 13:37 UTC, closed without merging